### PR TITLE
PR to support dimmer, and various upgrade based on tuya fetch

### PR DESCRIPTION
**Pull request by aurelihein**
Guess the correct function name from tuya, Adapt the domoticz percent to real values from tuya, Support Dimmer(test with MS-105)

### CODE REVIEW

**Comment by Xenomes** [comment]
Thank you for the modification for dimmer control,  I will integrate it with the Heater branche there is a lot changed the last days. It was basic the development branche 😅

**Comment by Xenomes** [comment]
Thank you for the modification for dimmer control,  I will integrate it with the Heater branche there is a lot changed the last days. It was basic the development branche 😅

**Comment by aurelihein** [comment]
FYI i just have tested your latest Master with all your further commits, and it does not work anymore ...

**Comment by Xenomes** [comment]
O that is not good, can you send me the dump.json? Your can create it by edit and run in python3 the debug_discovery.py from the tools directory. Please specify the device that is giving the problem.
Edit: In the develop 1.2.6 the dimmer is fixed.

**Pull request merged**
