### PR TITLE
Adding a power meter with dual channel like this.

### PR DESCRIPTION
**Pull request by romaint2b**
https://fr.aliexpress.com/item/1005007269856571.html

It's recognized as cz in Tuya , not powermeter (cz= switch or sensor). I add the device creation from 19 to 22 (channel A & B, forward and reverse energy) and power storage. I use direction in order to set to 0 the other direction and avoid measurement error. For example, if channel A is forward, it's reverse counter will be at 0.

For the moment this code is not running on my real server but in a sandbox server and it seems to work (but it's difficult to say if it's 100% good due to cloudy weather (few electricity produced by solar panes)).

### CODE REVIEW

**Comment by Xenomes** [comment]
Was looking good, hopefully the real life test is also a succes.

**Comment by romaint2b** [comment]
I try it for 5 minuts yesterday...today it was rainy. So impossible to try the REVERSE<>FORWARD switch and have a nice testing data. I'll make a reply in this thread when really validated (immediate power consomption and total power recording).

**Comment by romaint2b** [comment]
Today was better. It works fine.

**Comment by Xenomes** [comment]
Thanks for the feed back!

**Pull request merged**
