### PR TITLE
Fix dimmer support since new master upgrade

### PR DESCRIPTION
**Pull request by aurelihein**
Fix dimmer support since new master upgrade broke it

### CODE REVIEW

**Comment by aurelihein** [comment]
Please take a look at the function improved searchCode : if in function you are looking for **bright_value** but the command supported is _bright_value_1_ it will guess it and return the correct function name from tuya functions dict
It should simplify a lot your code

**Comment by Xenomes** [comment]
Hi, unfortunately your fork was out of date. There was a lot of code changed between version 1.2.5 and 1.2.6 see the compare of your pull request. There is also a fix of the 'bright_value_1' in there.
I love that you help improve the code!

**Comment by Xenomes** [comment]
Did a merge of your code in a branch to test: https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/tree/test_aurelihein

**Comment by Xenomes** [comment]
Changed to your search code, Thanks!

**Comment by aurelihein** [comment]
FYI I get back to https://github.com/Xenomes/Domoticz-TUYA-Plugin, since register on the pltaform is a pain and is not free anymore ... Eventually Domoticz-TUYA-Plugin  works straight without needing any registration and is stable

**Comment by Xenomes** [comment]
Yes, that plugin is a lot easier.

**Pull request closed without merging**
